import { definePrompt } from 'cz-git';

export default definePrompt({
  messages: {
    type: '커밋 타입을 선택하세요:',
    scope: '변경 범위를 입력하세요 (선택사항):',
    customScope: '변경 범위를 입력하세요:',
    subject: '변경 사항에 대한 간단한 설명을 작성하세요:\n',
    body: '상세한 설명을 입력하세요 (선택사항). "|"로 줄바꿈:\n',
    breaking: 'Breaking Changes를 적어주세요 (선택사항). "|"로 줄바꿈:\n',
    footerPrefixesSelect: '관련 이슈 타입을 선택하세요 (선택사항):',
    customFooterPrefix: '이슈 접두사를 입력하세요:',
    footer: '이슈 번호를 입력하세요. 예: #31, #34:\n',
    confirmCommit: '위 내용으로 커밋하시겠습니까?',
  },
  types: [
    { value: 'feat', name: 'feat:     ✨ 새로운 기능 추가', emoji: '✨' },
    { value: 'fix', name: 'fix:      🐛 버그 수정', emoji: '🐛' },
    { value: 'docs', name: 'docs:     📝 문서 수정', emoji: '📝' },
    { value: 'style', name: 'style:    💄 코드 포맷팅, 세미콜론 등', emoji: '💄' },
    { value: 'refactor', name: 'refactor: ♻️  코드 리팩토링', emoji: '♻️' },
    { value: 'perf', name: 'perf:     ⚡️ 성능 개선', emoji: '⚡️' },
    { value: 'test', name: 'test:     ✅ 테스트 추가/수정', emoji: '✅' },
    { value: 'build', name: 'build:    📦 빌드 시스템, 의존성 수정', emoji: '📦' },
    { value: 'ci', name: 'ci:       🔄 CI 설정 파일 수정', emoji: '🔄' },
    { value: 'chore', name: 'chore:    🔧 기타 변경사항', emoji: '🔧' },
    { value: 'revert', name: 'revert:   ⏪ 커밋 되돌리기', emoji: '⏪' },
  ],
  useEmoji: true,
  emojiAlign: 'center',
  scopes: ['core', 'docs'],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  customScopesAlias: 'custom',
  emptyScopesAlias: 'empty',
  upperCaseSubject: null,
  markBreakingChangeMode: true,
  allowBreakingChanges: ['feat', 'fix'],
  breaklineNumber: 100,
  breaklineChar: '|',
  skipQuestions: [],
  issuePrefixes: [
    { value: 'closes', name: 'closes:   이슈 해결 (자동 close)' },
    { value: 'fixes', name: 'fixes:    버그 수정 (자동 close)' },
    { value: 'refs', name: 'refs:     참조' },
  ],
  customIssuePrefixAlign: 'top',
  emptyIssuePrefixAlias: '건너뛰기',
  customIssuePrefixAlias: '직접 입력',
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  confirmColorize: true,
  maxHeaderLength: Infinity,
  maxSubjectLength: Infinity,
  minSubjectLength: 0,
});
